account:
  access_key: "ACCESS KEY"
  secret_key: "SECRET KEY"
trade:
  dialect: "binance"
  symbol: "ETHUSDT"
  interval: "15m"
  leverage: 3
  histKrange: 201
  margin: 0.00
  marginRatio: 98.00
  marginLimit: 100.00
tune:
  tp_pos_qty: 7
  cross_offset: 0.50